;;; doubley link solution with O(1)

(define (make-two-way-deque) (cons (make-deque) (make-deque)))
(define (make-deque) (cons '() '()))
(define (empty-deque? deque) (null? (front-ptr (forward deque))))
(define (set-front-ptr! deque item) (set-car! deque item))
(define (set-rear-ptr! deque item) (set-cdr! deque item))
(define (front-deque deque) (car deque))
(define (rear-deque deque) (cdr deque))

(define (forward-deque two-way-deque)
  (if (pair? (car deque))
      (caar deque)
      (error "ERROR forward -- deque not have a forward list" reque)))
(define (reverse-deque two-way-deque)
  (if (pair? (cdr deque))
      (cadr deque)
      (error "ERROR reverse -- deque not have a reverse list" deque)))
(define (front-insert-deque! two-way-deque)
  (let ((new-pair (cons item '())))
    (cond ((empty-deque? deque)
           (set-front-ptr! (forward two-way-deque) new-pair)
           (set-rear-ptr! (forward two-way-deque) new-pair)
           (set-front-ptr! (reverse two-way-deque) new-pair)
           (set-rear-ptr! (reverse two-way-deque) new-pair))
          (else
           (set-cdr! (rear-ptr (forward deque)) new-pair)
           (set-cdr! ())))))
