(load "insert!.scm")
(load "lookup.scm")
(load "make-table.scm")
(load "agenda-ops.scm")
(load "make-wire.scm")
(load "full-adder.scm")
(load "3.28.scm")
(load "and-gate.scm")
(load "after-delay.scm")
(load "queue-ops.scm")
(load "inverter.scm")
(load "probe.scm")
(load "propagate.scm")

(define the-agenda (make-agenda))
(define inverter-delay 2)
(define and-gate-delay 3)
(define or-gate-delay 5)
(define input-1 (make-wire))
(define input-2 (make-wire))
(define sum (make-wire))
(define carry (make-wire))

(probe 'sum sum)
(probe 'carry carry)
(half-adder input-1 input-2 sum carry)
(set-signal! input-1 1)
(propagate)
(set-signal! input-2 1)
(propagate)
